"""
本機 D1 / smoke test 用的 seed sizing 列產生器（不碰任何資料庫）
------------------------------------------------------------
    python -m core.sizing.seed_fixture        # 輸出 SQL，貼回 seed/seed.template.sql 的 D.3 GENERATED 區塊

輸入 = core.pricing.seed_fixture.seed_pricings()（與 seed 定價列同一份結果）；sizing = core.sizing.engine.size_portfolio
（與 production 同一函式，risk-v1）。T = seed BASE − 1 分鐘（token {{NOW:-1m}}）；明日 3 場同一個 betting day
（token {{TPEDATE:+1}}）。輸出列 warnings 含 "seed_fixture"（來自定價列）。
"""
from __future__ import annotations

import json
from datetime import timedelta

from ..pricing.seed_fixture import BASE, _sql, seed_pricings
from .engine import candidates_from_market_pricing, size_portfolio
from .job import COLUMNS, JSON_COLUMNS
from .policy import PRODUCTION_RISK_POLICY

AS_OF = BASE - timedelta(minutes=1)
AS_OF_TOKEN = "{{NOW:-1m}}"
DAY_TOKEN = "{{TPEDATE:+1}}"
GAME_START = BASE + timedelta(hours=8)          # 只用於「未開賽」檢查；betting_day 以 token 寫入


def generate(root=None) -> str:
    art, pricings = seed_pricings(root)
    cands, where = [], {}
    for mp, r, tok, as_of_tok, pred_tok, nba_id in pricings:
        for c in candidates_from_market_pricing(mp, game_start_utc=GAME_START):
            cands.append(c)
            where[(c.game_id, c.source, c.market, c.side)] = (r, tok, nba_id)
    results = size_portfolio(cands, as_of=AS_OF, policy=PRODUCTION_RISK_POLICY)
    out = []
    for res in results:
        r, tok, nba_id = where[(res.game_id, res.source, res.market, res.side)]
        snap = (f"(SELECT o.id FROM odds_snapshots o WHERE o.game_id = g.id AND o.source = '{r['source']}' "
                f"AND o.market = '{r['market']}' AND o.bookmaker IS NULL AND o.fetched_at = '{tok}')")
        vals = []
        for c in COLUMNS:
            v = getattr(res, c)
            if c == "market_pricing_snapshot_id":
                vals.append(f"(SELECT m.id FROM market_pricing_snapshots m WHERE m.odds_snapshot_id = {snap} "
                            f"AND m.side = '{res.side}' AND m.pricing_version = '{res.pricing_version}')")
            elif c == "odds_snapshot_id":
                vals.append(snap)
            elif c == "prediction_id":
                vals.append("(SELECT p.id FROM predictions p WHERE p.game_id = g.id AND "
                            "p.model_version = 'elo-v0.1-seed')")
            elif c == "game_id":
                vals.append("g.id")
            elif c == "betting_day":
                vals.append(f"'{DAY_TOKEN}'")
            elif c == "analysis_as_of":
                vals.append(f"'{AS_OF_TOKEN}'")
            elif c == "pricing_analysis_as_of":
                vals.append(f"(SELECT m.analysis_as_of FROM market_pricing_snapshots m WHERE m.odds_snapshot_id = "
                            f"{snap} AND m.side = '{res.side}')")
            elif c == "odds_fetched_at":
                vals.append(f"'{tok}'")
            elif c in JSON_COLUMNS:
                vals.append(_sql(json.dumps(v, ensure_ascii=False, allow_nan=False)))
            elif isinstance(v, bool):
                vals.append("TRUE" if v else "FALSE")
            else:
                vals.append(_sql(v))
        out.append(f"INSERT INTO bet_sizing_snapshots ({', '.join(COLUMNS)})\nSELECT {', '.join(vals)}"
                   f"\nFROM games g WHERE g.nba_game_id = '{nba_id}';")
    header = (f"-- >>> GENERATED by `cd pipeline && python -m core.sizing.seed_fixture`（artifact {art.artifact_version}，"
              f"{PRODUCTION_RISK_POLICY.version}）\n"
              "-- 輸入 = 上方 seed 定價列；Kelly / caps / exposure = core.sizing.engine.size_portfolio（與 production 同一函式）。"
              "勿手動修改。\n")
    return header + "\n".join(out) + "\n-- <<< GENERATED (D.3)\n"


if __name__ == "__main__":
    print(generate(), end="")
